# Week 1 — Day 3: Extra Practice (NumPy)

Additional self-practice exercises to strengthen NumPy fundamentals beyond the official Hands-On Lab.

---

## Exercise 1: Array Creation

Creating arrays using different NumPy methods: `randint`, `zeros`, and `linspace`.

In [1]:
import numpy as np
arr = np.random.randint(1, 101, size= 10)
print(arr)

[76 73 30 80 13 21 41 81 93 15]


In [3]:
import numpy as np
arr = np.zeros((3, 5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
arr = np.linspace(0, 50, 6)
print(arr)

[ 0. 10. 20. 30. 40. 50.]


## Practical Scenarios

The following exercises apply NumPy concepts (array creation, indexing, 
broadcasting, and vectorized operations) to realistic, real-world scenarios 
rather than isolated function calls — reflecting how NumPy is actually used 
in data science workflows.

---

### Exercise A: Student Grades
Given a 2D array representing grades for 4 students across 3 subjects, 
we add bonus points to one subject, compute each student's average, 
and identify the top-performing student.


In [10]:
grades = np.array([[80, 90, 70],
                    [60, 85, 95],
                    [75, 88, 92],
                    [50, 60, 70]])
grades[:, 0] = grades[:, 0] + 5
print (grades)
top_student_index = np.argmax(student_averages)
print("Top student index:", top_student_index)
print("Top student average:", student_averages[top_student_index])


[[85 90 70]
 [65 85 95]
 [80 88 92]
 [55 60 70]]
Top student index: 2
Top student average: 86.66666666666667


### Exercise B: Temperature Conversion

We have a 1D array of daily temperatures in Celsius for one week.
**Tasks:**
1. Convert all temperatures to Fahrenheit using vectorized operations.
2. Print which days had a temperature above 25°C.

In [16]:
temps_celsius = np.array([22, 25, 19, 30, 28, 24, 21])
print("Celsius:", temps_celsius)
F = temps_celsius * 9/5 + 32
print(F)
Hottest_days = temps_celsius[temps_celsius > 25]
print(Hottest_days)
hottest_days_index = np.where(temps_celsius > 25)
print("Day positions:", hottest_days_index)


Celsius: [22 25 19 30 28 24 21]
[71.6 77.  66.2 86.  82.4 75.2 69.8]
[30 28]
Day positions: (array([3, 4]),)


### Exercise C: Shopping Bill

Given arrays of prices and quantities for different products, we compute 
the cost per item, the total bill, and apply a discount — all using 
vectorized operations.

In [17]:
prices = np.array([10, 25, 5, 40])
quantities = np.array([2, 1, 10, 3])
item_costs = prices * quantities
print("Cost per item:", item_costs)
total_bill = item_costs.sum()
print("Total bill:", total_bill)
discount = 0.10
final_price = total_bill * (1 - discount)
print("Final price after 10% discount:", final_price)

Cost per item: [ 20  25  50 120]
Total bill: 215
Final price after 10% discount: 193.5


### Exercise D: Image Brightness (Advanced Broadcasting)

Given a 2D array representing a grayscale image (values 0-255), we adjust 
brightness, clip values to a valid range, and invert the image.

In [21]:
image = np.array([[100, 150, 200],
                   [50, 75, 125],
                   [10, 20, 30]])
Brilliant_Image = image +30
print(Brilliant_Image)
clipped_image = np.clip(Brilliant_Image,0,255)
The_inverse_matrix = 255 - clipped_image 
print(The_inverse_matrix)


[[130 180 230]
 [ 80 105 155]
 [ 40  50  60]]
[[125  75  25]
 [175 150 100]
 [215 205 195]]
