# Week 1 — Day 3: NumPy Numerical Computing

## Objective
Practicing array creation, indexing, slicing, boolean masking, and broadcasting using **NumPy**.

---


## Step 1: Array Creation

We create a `4x4` 2D array containing values from 1 to 16 using `np.arange()` and `.reshape()`, 
then inspect its **shape** and **dtype**.

In [2]:
import numpy as np
arr = np.arange(1,17).reshape(4,4)
print(arr)
print("Shape:", arr.shape)
print("Dtype:", arr.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Shape: (4, 4)
Dtype: int64


## Step 2: Indexing & Slicing

We extract the **second column** (`arr[:, 1]`) and the **last row** (`arr[-1, :]`) 
using NumPy's slicing syntax.

In [3]:
second_column = arr[:, 1]
last_row = arr[-1, :]

print("Second column:", second_column)
print("Last row:", last_row)

Second column: [ 2  6 10 14]
Last row: [13 14 15 16]


## Step 3: Boolean Masking

We compute the mean of the array, then use a **boolean mask** (`arr > mean`) 
to select only the values greater than the mean.

In [4]:
mean_value = arr.mean()
above_mean = arr[arr > mean_value]

print("Mean value:", mean_value)
print("Values above mean:", above_mean)

Mean value: 8.5
Values above mean: [ 9 10 11 12 13 14 15 16]


## Step 4: Broadcasting

We add a 1D array (`row_to_add`) to every row of the 2D array using **broadcasting**, 
then manually verify the result for the first row.

In [7]:
row_to_add = np.array([100, 200, 300, 400])
result = arr + row_to_add

print("Original array:\n", arr)
print("\nRow to add:", row_to_add)
print("\nResult after broadcasting:\n", result)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row to add: [100 200 300 400]

Result after broadcasting:
 [[101 202 303 404]
 [105 206 307 408]
 [109 210 311 412]
 [113 214 315 416]]


### Manual Verification
We manually compute the broadcasting result for row 0 and confirm it matches NumPy's output.

In [8]:
manual_check = arr[0] + row_to_add
print("Manual check for row 0:", manual_check)
print("Matches broadcasting result?", np.array_equal(manual_check, result[0]))

Manual check for row 0: [101 202 303 404]
Matches broadcasting result? True


## Summary

In this notebook, we practiced:
- Creating NumPy arrays with `arange()` and `reshape()`
- Indexing and slicing 2D arrays
- Boolean masking to filter values by condition
- Broadcasting to apply operations across array shapes

These are the foundational NumPy skills used throughout the rest of the AI/ML program.